### ISSUE TITLE
label:"good first issue" How to keep channels repeating themself

### ISSUE THREAD

**Issue by Kick4U2** [deanochips/HLS-XMLTV---Home-Broadcasting#1]
Hello and first of all... Thank you!

I just found this software and worked on it tonight and am very excited!  It is working really well.
I need to look into this much deeper, but wondered what your method is for refreshing the channel?  I assume you have cron job every hour or so running cron.sh or maybe even shorter i.e 15 mins?

It will be difficult, but I think it's possible to keep track of the end time of a channel and save this to a variable.  This variable would be compared for the next channel and stores the first upcoming end time.  This way at the end of running the app, the variable would have the end time of the channel finishing first.

In this way the script can run as a service and would refresh whenever the current time reaches the variable stored (shortest channel end time).

Cheers!

**Comment by Kick4U2** [comment]
Made a customized version of your software to loop channel indefinitely.  Running three streams pre-encoded the same work with nearly no CPU utilization so far.

**Comment by Toei79** [comment]
where you leave it? its anyway to add logos to script, and epg its not scrapping rightly just some . sorry not too much movement here so i ask right here.
